<?php
namespace Grafikart\RecaptchaBundle;
/**
 * Created by PhpStorm.
 * User: safa
 * Date: 07/02/2019
 * Time: 8:54 AM
 */
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
Class RecaptchaBundle extends Bundle{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new RecaptchaCompilerPass());
    }


}